# prod: sellers_bot 
services:
  axiomai_clients_bot:
    build: .
    container_name: axiomai_clients_bot
    command: uv run python -m src.app.clients_bot.run
    env_file:
      - .env        # на проде тут лежит REDIS_URL=redis://default:...@194.87.86.12:6379/2
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always

  axiomai_sellers_bot:
    build: .
    container_name: axiomai_sellers_bot
    command: uv run python -m src.app.sellers_bot.run
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always


# # develop: redis + postgres + + clients_bot + sellers_bot
# services:
#   postgres:
#     image: postgres:16
#     container_name: local_postgres
#     restart: always
#     environment:
#       POSTGRES_USER: axiomai
#       POSTGRES_PASSWORD: axiomai_pass
#       POSTGRES_DB: axiomai_dev
#     ports:
#       - "5435:5432"
#     volumes:
#       - ./pgdata_dev:/var/lib/postgresql/data
#   redis:
#     image: redis:7
#     container_name: redis
#     restart: always
#     ports:
#       - "6380:6379"
#   clients_bot:
#       build: .
#       container_name: clients_bot
#       command: uv run python -m src.app.clients_bot.run
#       env_file: 
#         - .env
#       depends_on:
#         - redis
#         - postgres
#       volumes:
#       - .:/app
#       - ./logs:/app/logs
#       restart: always
#   sellers_bot:
#     build: .
#     container_name: sellers_bot
#     command: uv run python -m src.app.sellers_bot.run
#     env_file: 
#       - .env
#     depends_on:
#       - redis
#       - postgres
#     volumes:
#       - .:/app
#       - ./logs:/app/logs
#     restart: always
