services:
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axiomai.tgbot.dev
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./axiomai:/app/axiomai
      - ./assets:/app/assets
      - ./sunny-might-477012-c4-04c66c69a92f.json:/app/sunny-might-477012-c4-04c66c69a92f.json:ro
    restart: unless-stopped
    command: "python -m axiomai.tgbot"
  observer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axiomai.observer.dev
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./axiomai:/app/axiomai
      - ./sunny-might-477012-c4-04c66c69a92f.json:/app/sunny-might-477012-c4-04c66c69a92f.json:ro
    restart: unless-stopped
    command: "python -m axiomai.observer"
  postgres_migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axiomai.postgres.migration.dev
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./axiomai:/app/axiomai
    command: "alembic upgrade head"
  postgres:
    container_name: axiomai.postgres.dev
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 30s
      retries: 3
    env_file:
      - ".env"
  redis:
    container_name: axiomai.redis.dev
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --no-auth-warning -a $$REDIS_PASSWORD ping | grep '^PONG$' || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 3
    env_file:
      - ".env"
    command:
      sh -c '
      redis-server
      --appendonly yes
      --requirepass $$REDIS_PASSWORD
      --bind 0.0.0.0'